FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /App
ADD ./Src/Api ./Src/Api
ADD ./Src/Application ./Src/Application
ADD ./Src/Infrastructure ./Src/Infrastructure
ADD ./Src/Domain ./Src/Domain

WORKDIR /App/Src/Api
RUN dotnet restore
RUN dotnet publish -c Release -o ../../Out

FROM mcr.microsoft.com/dotnet/aspnet:7.0

WORKDIR /Api
COPY --from=build ./App/Out .

ENTRYPOINT dotnet Api.dll